services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coffee-rt
      POSTGRES_PASSWORD: coffee-rt_password
      POSTGRES_DB: coffee-rt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coffee-rt -d coffee-rt"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee-rt

  db-migrate:
    container_name: db-migrate
    build:
      context: .
      dockerfile: .dev/db-migrate/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://coffee-rt:coffee-rt_password@postgres:5432/coffee-rt
      POSTGRES_SCHEMA: coffee_rt
    networks:
      - coffee-rt

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - coffee-rt
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis-init:
    container_name: redis-init
    build:
      context: .
      dockerfile: .dev/redis-init/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_INIT: ${REDIS_INIT}
    networks:
      - coffee-rt

  cafe-order-api:
    container_name: cafe-order-api
    build:
      context: .
      dockerfile: backend/cafe_order_api/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      redis-init:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: coffee-rt
      POSTGRES_PASSWORD: coffee-rt_password
      POSTGRES_DB: coffee-rt
      POSTGRES_SCHEMA: coffee_rt
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - coffee-rt

  cafe-dashboard:
    container_name: cafe-dashboard
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - cafe-order-api
    networks:
      - coffee-rt

  cafe-order-aggregator:
    container_name: cafe-order-aggregator
    build:
      context: .
      dockerfile: backend/cafe_order_aggregator/Dockerfile.cron
    depends_on:
      db-migrate:
        condition: service_completed_successfully
      redis-init:
        condition: service_completed_successfully
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: coffee-rt
      POSTGRES_PASSWORD: coffee-rt_password
      POSTGRES_DB: coffee-rt
      POSTGRES_SCHEMA: coffee_rt
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - coffee-rt
    restart: unless-stopped

networks:
  coffee-rt:
    driver: bridge

volumes:
  postgres_data:
