apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager
  labels:
    {{- include "flink.labels" . | nindent 4 }}
    app.kubernetes.io/component: jobmanager
spec:
  type: {{ .Values.jobmanager.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.jobmanager.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    - name: blob-server
      port: 6124
      targetPort: blob-server
      protocol: TCP
    - name: webui
      port: {{ .Values.jobmanager.service.port }}
      targetPort: webui
      protocol: TCP
  selector:
    {{- include "flink.jobmanager.selectorLabels" . | nindent 4 }}
