apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
    {{- include "flink.labels" . | nindent 4 }}
    app.kubernetes.io/component: taskmanager
spec:
  replicas: {{ .Values.taskmanager.replicas }}
  selector:
    matchLabels:
      {{- include "flink.taskmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flink.taskmanager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: taskmanager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["taskmanager"]
          ports:
            - name: data
              containerPort: 6121
              protocol: TCP
            - name: rpc
              containerPort: 6122
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.taskmanager.resources | nindent 12 }}
          volumeMounts:
            - name: flink-config
              mountPath: /opt/flink/conf/flink-conf.yaml
              subPath: flink-conf.yaml
            - name: flink-config
              mountPath: /opt/flink/conf/log4j-console.properties
              subPath: log4j-console.properties
      volumes:
        - name: flink-config
          configMap:
            name: {{ include "flink.fullname" . }}-config
