apiVersion: v2
name: coffee-rt
description: A Helm chart for the Coffee RT application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: api
    version: "0.1.0"
    condition: api.enabled
  - name: aggregator
    version: "0.1.0"
    condition: aggregator.enabled
  - name: frontend
    version: "0.1.0"
    condition: frontend.enabled
  - name: postgresql
    version: "16.4.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "20.6.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
