apiVersion: v2
name: coffee-rt
description: A Helm chart for the Coffee RT application
type: application
version: 0.2.0
appVersion: "1.0.0"

dependencies:
  - name: db-migrate
    version: "0.1.0"
    condition: db-migrate.enabled
  - name: api
    version: "0.1.0"
    condition: api.enabled
  - name: aggregator
    version: "0.1.0"
    condition: aggregator.enabled
  - name: frontend
    version: "0.1.0"
    condition: frontend.enabled
  - name: stream-worker
    version: "0.1.0"
    condition: stream-worker.enabled
  - name: flink
    version: "0.1.0"
    condition: flink.enabled
  - name: flink-job
    version: "0.1.0"
    condition: flink-job.enabled
  - name: postgresql
    version: "18.1.13"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "24.0.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka-confluent
    version: "0.1.0"
    condition: kafka-confluent.enabled
  - name: prometheus
    version: "27.50.1"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: loki
    version: "6.48.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: promtail
    version: "6.17.1"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
  - name: grafana
    version: "10.3.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
