{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "load-tester.fullname" . }}
  labels:
    {{- include "load-tester.labels" . | nindent 4 }}
  {{- if .Values.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
  {{- end }}
{{- end }}
